# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-13 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190613_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image?default.png', upload_to='image/%Y/%m', verbose_name='头像'),
        ),
    ]
